plugins:
  - jekyll-paginate

collections:
  services:
    output: true
    permalink: revops/:collection/:name
  posts:
    output: true
    permalink: revops/:collection/:name

paginate: 12
paginate_path: revops/blog/page:num
